/**
 * @fileoverview Build script for Anime4K Web Upscaler Extension
 * Concatenates all source files into single distributable files.
 * No external bundler dependencies required.
 * @version 2.8.1
 */

const fs = require('fs');
const path = require('path');

// Build configuration
const config = {
    srcDir: 'src',
    distDir: 'dist',

    // Files to bundle for content script (order matters!)
    contentScriptFiles: [
        'src/config.js',
        'src/utils/webgl-utils.js',
        'src/utils/dom-utils.js',
        'src/utils/shader-utils.js',
        'src/utils/resolution-utils.js',
        'src/core/video-processor.js',
        'src/content-main.js'
    ],

    // Files to bundle for popup
    popupFiles: [
        'src/config.js',
        'src/popup-main.js'
    ],

    // Files to bundle for worker
    workerFiles: [
        'src/config.js',
        'src/utils/webgl-utils.js',
        'src/utils/shader-utils.js',
        'src/worker-main.js'
    ],

    // Static files to copy
    staticFiles: [
        'popup.html',
        'manifest.json',
        'net_request_rules.json'
    ],

    // Directories to copy
    staticDirs: [
        'Model'
    ]
};

// Utility functions
function ensureDir(dirPath) {
    if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
    }
}

function readFile(filePath) {
    if (fs.existsSync(filePath)) {
        return fs.readFileSync(filePath, 'utf8');
    }
    console.warn(`Warning: File not found: ${filePath}`);
    return '';
}

function writeFile(filePath, content) {
    ensureDir(path.dirname(filePath));
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Created: ${filePath}`);
}

function copyFile(src, dest) {
    ensureDir(path.dirname(dest));
    fs.copyFileSync(src, dest);
    console.log(`Copied: ${src} -> ${dest}`);
}

function copyDir(src, dest) {
    ensureDir(dest);
    const entries = fs.readdirSync(src, { withFileTypes: true });

    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);

        if (entry.isDirectory()) {
            copyDir(srcPath, destPath);
        } else {
            copyFile(srcPath, destPath);
        }
    }
}

function bundleFiles(files, outputPath) {
    console.log(`\nBundling ${files.length} files -> ${outputPath}`);

    let content = `/**
 * @fileoverview Bundled file for Anime4K Web Upscaler
 * Auto-generated by build.js - DO NOT EDIT DIRECTLY
 * Generated: ${new Date().toISOString()}
 */

`;

    for (const file of files) {
        if (fs.existsSync(file)) {
            const fileContent = readFile(file);
            content += `\n// ==================== ${file} ====================\n`;
            content += fileContent;
            content += '\n';
        } else {
            console.warn(`  Skipping missing file: ${file}`);
        }
    }

    writeFile(outputPath, content);
}

function updateManifestForDist() {
    const manifestPath = path.join(config.distDir, 'manifest.json');
    const manifest = JSON.parse(readFile(manifestPath));

    // Update content scripts to use bundled file
    manifest.content_scripts[0].js = [
        'Model/debug.js',
        'Model/anime4k_fast.js',
        'Model/anime4k_hq.js',
        'Model/fsr.js',
        'Model/xbrz.js',
        'Model/cas.js',
        'Model/bicubic.js',
        'Model/lanczos3.js',
        'Model/realsr.js',
        'Model/esrgan.js',
        'content.js'
    ];

    writeFile(manifestPath, JSON.stringify(manifest, null, 2));
    console.log('Updated manifest.json for dist');
}

// Main build function
function build() {
    console.log('='.repeat(50));
    console.log('Anime4K Web Upscaler - Build Script');
    console.log('='.repeat(50));

    // Clean and create dist directory
    if (fs.existsSync(config.distDir)) {
        fs.rmSync(config.distDir, { recursive: true });
    }
    ensureDir(config.distDir);

    // Bundle content script
    bundleFiles(config.contentScriptFiles, path.join(config.distDir, 'content.js'));

    // Bundle popup script
    bundleFiles(config.popupFiles, path.join(config.distDir, 'popup.js'));

    // Bundle worker script
    bundleFiles(config.workerFiles, path.join(config.distDir, 'worker.js'));

    // Copy static files
    console.log('\nCopying static files...');
    for (const file of config.staticFiles) {
        if (fs.existsSync(file)) {
            copyFile(file, path.join(config.distDir, file));
        }
    }

    // Copy static directories
    console.log('\nCopying static directories...');
    for (const dir of config.staticDirs) {
        if (fs.existsSync(dir)) {
            copyDir(dir, path.join(config.distDir, dir));
        }
    }

    // Update manifest for dist
    updateManifestForDist();

    console.log('\n' + '='.repeat(50));
    console.log('Build complete! Output in:', config.distDir);
    console.log('='.repeat(50));
}

// Watch mode
function watch() {
    console.log('Watching for changes...');

    const watchDirs = ['src', 'Model'];

    for (const dir of watchDirs) {
        if (fs.existsSync(dir)) {
            fs.watch(dir, { recursive: true }, (eventType, filename) => {
                console.log(`\nChange detected: ${filename}`);
                build();
            });
        }
    }

    // Initial build
    build();
}

// CLI handling
const args = process.argv.slice(2);

if (args.includes('--watch')) {
    watch();
} else {
    build();
}
